import time

import numexpr as num
from colorama import init
from colorama import Fore, Back
import pyautogui as py

init()
try:
    x = 0
    while x == 0:
        print(Fore.YELLOW)
        exam = py.prompt("Введите ваш пример", "Математическая операция ")
        res = num.evaluate(exam)
        print(exam, "=", res)
        print(Fore.LIGHTBLUE_EX)
        py.alert(res, "Answer", button="Thanks")
        print("Україна, понад усе!")
        print(Fore.YELLOW)
        exam = py.prompt("Введите ваш пример", "Математическая операция ")
        res = num.evaluate(exam)
        print(exam, "=", res)
        print(Fore.LIGHTBLUE_EX)
        py.alert(res, "Answer", button="Thanks")
        print("Слава Україні!")
        print(Fore.YELLOW)
        exam = py.prompt("Введите ваш пример", "Математическая операция ")
        res = num.evaluate(exam)
        print(exam, "=", res)
        print(Fore.LIGHTBLUE_EX)
        py.alert(res, "Answer", button="Thanks")
        print("Героям Слава!")
        print(Fore.YELLOW)
        exam = py.prompt("Введите ваш пример", "Математическая операция ")
        res = num.evaluate(exam)
        print(exam, "=", res)
        print(Fore.LIGHTBLUE_EX)
        py.alert(res, "Answer", button="Thanks")
        print("Слава Нації!")
        print(Fore.YELLOW)
        exam = py.prompt("Введите ваш пример", "Математическая операция ")
        res = num.evaluate(exam)
        print(exam, "=", res)
        print(Fore.LIGHTBLUE_EX)
        py.alert(res, "Answer", button="Thanks")
        print("Смерть ворогам! ")
except ValueError:
    print(Fore.RED)
    print(Back.BLACK)
    print("Если вам нужен калькулятор, перезапустите его) ")
    time.sleep(4)
    print('А я спать...')
    time.sleep(2)
except SyntaxError:
    print("Возможно вы ввели что-то не так...")
    print('Попробуйте еще раз) ')
    time.sleep(1)
    x = 0
    while x == 0:
        print(Fore.YELLOW)
        exam = py.prompt("Введите ваш пример", "Математическая операция ")
        res = num.evaluate(exam)
        print(exam, "=", res)
        print(Fore.LIGHTBLUE_EX)
        py.alert(res, "Answer", button="Thanks")
        print("Україна, понад усе!")
        print(Fore.YELLOW)
        exam = py.prompt("Введите ваш пример", "Математическая операция ")
        res = num.evaluate(exam)
        print(exam, "=", res)
        print(Fore.LIGHTBLUE_EX)
        py.alert(res, "Answer", button="Thanks")
        print("Слава Україні!")
        print(Fore.YELLOW)
        exam = py.prompt("Введите ваш пример", "Математическая операция ")
        res = num.evaluate(exam)
        print(exam, "=", res)
        print(Fore.LIGHTBLUE_EX)
        py.alert(res, "Answer", button="Thanks")
        print("Героям Слава!")
        print(Fore.YELLOW)
        exam = py.prompt("Введите ваш пример", "Математическая операция ")
        res = num.evaluate(exam)
        print(exam, "=", res)
        print(Fore.LIGHTBLUE_EX)
        py.alert(res, "Answer", button="Thanks")
        print("Слава Нації!")
        print(Fore.YELLOW)
        exam = py.prompt("Введите ваш пример", "Математическая операция ")
        res = num.evaluate(exam)
        print(exam, "=", res)
        print(Fore.LIGHTBLUE_EX)
        py.alert(res, "Answer", button="Thanks")
        print("Смерть ворогам! ")
except AssertionError:
    print(Fore.RED)
    print(Back.BLACK)
    print("Если вам нужен калькулятор, перезапустите его) ")
    time.sleep(1)
    print('А я спать...')
    time.sleep(2)
