import time
import turtle as tur
brez = tur.Pen()
while True:

    print('Type of program: \'1 - Зсув\', \'2 - Масштабування\', \'3 - Відображення\', \'4 - Переведення\' ')

    type_of_prog = int(input('Your choice: '))
    if type_of_prog == 0:
        break
    radius = int(input('Your radius: '))
    if type_of_prog == 1:
        brez.reset()
        brez.pensize(3)
        brez.begin_fill()
        brez.color('yellow', 'black')
        brez.circle(radius)
        brez.end_fill()

        #Перемещение (Shift on )

        shift = input('Your shift on what axis: Ox, Oy, -Ox, -Oy ')
        if shift == 'Ox':
            brez.begin_fill()
            brez.color('red', 'black')
            shift_Ox = int(input('Shift on pixel: '))
            brez.penup()
            brez.goto(shift_Ox, 0)
            brez.pendown()
            brez.circle(radius)
            brez.end_fill()
            time.sleep(2)
        if shift == 'Oy':
            brez.begin_fill()
            brez.color('green', 'black')
            shift_Ox = int(input('Shift on pixel: '))
            brez.penup()
            brez.goto(0, shift_Ox)
            brez.pendown()
            brez.circle(radius)
            brez.end_fill()
            time.sleep(2)
        if shift == '-Ox':
            brez.begin_fill()
            brez.color('red', 'black')
            shift_Ox = int(input('Shift on pixel: '))
            brez.penup()
            brez.goto(-shift_Ox, 0)
            brez.pendown()
            brez.circle(radius)
            brez.end_fill()
            time.sleep(2)
        if shift == '-Oy':
            brez.begin_fill()
            brez.color('green', 'black')
            shift_Ox = int(input('Shift on pixel: '))
            brez.penup()
            brez.goto(0, -shift_Ox)
            brez.pendown()
            brez.circle(radius)
            brez.end_fill()
            time.sleep(2)
    if type_of_prog == 2:
        brez.reset()
        brez.begin_fill()
        brez.color('black', 'yellow')
        brez.circle(radius)
        brez.end_fill()
        print('Do you want to zoom in or out? ')
        print('1 - Zoom in, 2 - out ')
        zoom_out = int(input('Your choise: '))
        in_times = float(input('Do you want zoom in or out in times: '))
        if zoom_out == 1:
            brez.penup()
            brez.goto(-200, -100)
            brez.pendown()
            radius_zoom = radius * in_times
            brez.begin_fill()
            brez.color('pink', 'green')
            brez.circle(radius_zoom)
            brez.end_fill()
            time.sleep(2)
        if zoom_out == 2:
            brez.penup()
            brez.goto(-200, -100)
            brez.pendown()
            radius_out = radius / in_times
            brez.begin_fill()
            brez.color('black', 'green')
            brez.circle(radius_out)
            brez.end_fill()
            time.sleep(2)
    if type_of_prog == 3:
        brez.reset()
        brez.begin_fill()
        brez.color('blue', 'red')
        brez.circle(radius)
        brez.right(180)
        print('Drawing in mirror image')
        brez.end_fill()
        brez.begin_fill()
        brez.color('red', 'blue')
        brez.circle(radius)
        brez.end_fill()
    if type_of_prog == 4:
        brez.reset()
        brez.begin_fill()
        brez.color('black', 'green')
        brez.circle(radius)
        brez.end_fill()
        time.sleep(2)
        brez.clear()
        goto_X = int(input('Coordinate by Ox: '))
        goto_Y = int(input('Coordinate by Oy: '))
        brez.penup()
        brez.goto(goto_X, goto_Y)
        brez.pendown()
        brez.begin_fill()
        brez.color('black', 'red')
        brez.circle(radius)
        brez.end_fill()
